package refs

import (
	"fmt"
	"strings"
)

const renderFileName = "REFERENCES.md"

// RenderMarkdown generates a REFERENCES.md from the references file.
func RenderMarkdown(projectName string, f *File) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# %s — References\n\n", projectName))
	b.WriteString("> *Every project stands on the shoulders of others.*\n\n")
	b.WriteString("This project's architecture and design decisions were shaped by the following projects.\n\n")

	if len(f.References) == 0 {
		b.WriteString("*No references yet.*\n")
		return b.String()
	}

	// Group by project
	grouped := map[string][]Reference{}
	order := []string{}
	for _, r := range f.References {
		if _, exists := grouped[r.Project]; !exists {
			order = append(order, r.Project)
		}
		grouped[r.Project] = append(grouped[r.Project], r)
	}

	// Dependency graph (text tree)
	b.WriteString("## Dependency Graph\n\n")
	b.WriteString("```\n")
	b.WriteString(fmt.Sprintf("%s\n", projectName))
	for i, project := range order {
		entries := grouped[project]
		isLast := i == len(order)-1
		name := shortName(project)

		if isLast {
			b.WriteString(fmt.Sprintf("└── %s\n", name))
		} else {
			b.WriteString(fmt.Sprintf("├── %s\n", name))
		}

		for j, e := range entries {
			isLastEntry := j == len(entries)-1
			var prefix string
			if isLast {
				prefix = "    "
			} else {
				prefix = "│   "
			}
			if isLastEntry {
				b.WriteString(fmt.Sprintf("%s└── %s\n", prefix, e.Learned))
			} else {
				b.WriteString(fmt.Sprintf("%s├── %s\n", prefix, e.Learned))
			}
		}
	}
	b.WriteString("```\n\n")

	// Detailed table
	b.WriteString("## References\n\n")
	b.WriteString("| Project | What we learned | Where we applied it |\n")
	b.WriteString("|---------|----------------|--------------------|\n")

	for _, r := range f.References {
		applied := r.Applied
		if applied == "" {
			applied = "—"
		}
		project := r.Project
		// Link to GitHub if it looks like owner/repo
		if strings.Count(project, "/") == 1 {
			project = fmt.Sprintf("[%s](https://github.com/%s)", r.Project, r.Project)
		}
		b.WriteString(fmt.Sprintf("| %s | %s | `%s` |\n", project, r.Learned, applied))
	}

	b.WriteString("\n---\n\n")
	b.WriteString(fmt.Sprintf("*%d references across %d projects — generated by [ossref](https://github.com/herfstvalt/ossref)*\n", len(f.References), len(order)))

	return b.String()
}

func shortName(project string) string {
	parts := strings.Split(project, "/")
	if len(parts) >= 2 {
		return parts[len(parts)-1]
	}
	return project
}
